MODEL_CHECKPOINT: "microsoft/deberta-v3-base"

DATASET_LABEL: "cardiffnlp/tweet_topic_single"
SOURCE_COLUMN: "text"
TARGET_COLUMN: "label"
MAX_SEQUENCE_LEN: 512

PATH_TO_RESULT_OUTPUT_DIR: "./results/"
PATH_TO_MODEL_OUTPUT_DIR: "./models/"

TRAIN: False
BATCH_SIZE: 2
EPOCHS: 10
LEARNING_RATE: 1e-6
WEIGHT_DECAY: 1e-4
EARLY_STOPPING_THRESHOLD: 5

SAMPLE_SIZE: 300